// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop__pch.h"

// Parameter definitions for Vtop___024root
constexpr CData/*3:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__TILE_ID;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__sim;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__debug;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__with_c;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__with_csr;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__with_mdu;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__mux__DOT__sim;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__PRE_REGISTER;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__DEBUG;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__MDU;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__COMPRESSED;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__ALIGN;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__state__DOT__WITH_CSR;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__state__DOT__ALIGN;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__state__DOT__MDU;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__decode__DOT__PRE_REGISTER;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__decode__DOT__MDU;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__bufreg__DOT__MDU;
constexpr CData/*0:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__mem_if__DOT__WITH_CSR;
constexpr CData/*1:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__CSR_SOURCE_CSR;
constexpr CData/*1:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__CSR_SOURCE_EXT;
constexpr CData/*1:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__CSR_SOURCE_SET;
constexpr CData/*1:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__CSR_SOURCE_CLR;
constexpr CData/*3:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__router_inst__DOT__MY_ID;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__boot_inst__DOT__IDLE;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__boot_inst__DOT__CMD;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__boot_inst__DOT__ADDR;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__boot_inst__DOT__READ;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__boot_inst__DOT__WRITE;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__boot_inst__DOT__DONE;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__memsize;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__RESET_STRATEGY;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__WITH_CSR;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__aw;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__regs;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__rf_width;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__rf_mem_if__DOT__depth;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__rf_mem_if__DOT__rf_regs;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__rf_mem_if__DOT__rf_depth;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__rf_mem_if__DOT__aw;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__width;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__reset_pc;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__reset_strategy;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_width;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__B;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__regs;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_l2d;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__mux__DOT__sim_sig_adr;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__mux__DOT__sim_halt_adr;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_ram_if__DOT__width;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_ram_if__DOT__W;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_ram_if__DOT__reset_strategy;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_ram_if__DOT__csr_regs;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_ram_if__DOT__B;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_ram_if__DOT__raw;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_ram_if__DOT__l2w;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_ram_if__DOT__aw;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_ram_if__DOT__ratio;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_ram_if__DOT__CMSB;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__rf_ram_if__DOT__l2r;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__WITH_CSR;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__W;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__B;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__RESET_STRATEGY;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__RESET_PC;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__state__DOT__RESET_STRATEGY;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__state__DOT__W;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__immdec__DOT__SHARED_RFADDR_IMM_REGS;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__immdec__DOT__W;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__bufreg__DOT__W;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__bufreg__DOT__B;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__bufreg2__DOT__W;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__bufreg2__DOT__B;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__ctrl__DOT__RESET_STRATEGY;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__ctrl__DOT__RESET_PC;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__ctrl__DOT__WITH_CSR;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__ctrl__DOT__W;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__ctrl__DOT__B;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__alu__DOT__W;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__alu__DOT__B;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__rf_if__DOT__WITH_CSR;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__rf_if__DOT__W;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__rf_if__DOT__B;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__mem_if__DOT__W;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__mem_if__DOT__B;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__RESET_STRATEGY;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__W;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__core_inst__DOT__servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__B;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__Tdly;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__Tcyc;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__Tckh;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__Tckl;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__tcs;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__tas;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__tds;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__tws;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__twis;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__tch;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__tah;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__tdh;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__twh;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__twih;
constexpr IData/*31:0*/ Vtop___024root::pbm_tile_full_pipeline_wrapper__DOT__dut__DOT__sram_inst__DOT__ta;


void Vtop___024root___ctor_var_reset(Vtop___024root* vlSelf);

Vtop___024root::Vtop___024root(Vtop__Syms* symsp, const char* namep)
    : __VdlySched{*symsp->_vm_contextp__}
 {
    vlSymsp = symsp;
    vlNamep = strdup(namep);
    // Reset structure values
    Vtop___024root___ctor_var_reset(this);
}

void Vtop___024root::__Vconfigure(bool first) {
    (void)first;  // Prevent unused variable warning
}

Vtop___024root::~Vtop___024root() {
    VL_DO_DANGLING(std::free(const_cast<char*>(vlNamep)), vlNamep);
}
