// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP_SUBSERVIENT_CORE_H_
#define VERILATED_VTOP_SUBSERVIENT_CORE_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop_subservient_core final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(i_clk,0,0);
        VL_IN8(i_rst,0,0);
        VL_IN8(i_timer_irq,0,0);
        VL_OUT8(o_sram_wdata,7,0);
        VL_OUT8(o_sram_wen,0,0);
        VL_IN8(i_sram_rdata,7,0);
        VL_OUT8(o_sram_ren,0,0);
        VL_OUT8(o_wb_sel,3,0);
        VL_OUT8(o_wb_we,0,0);
        VL_OUT8(o_wb_stb,0,0);
        VL_IN8(i_wb_ack,0,0);
        CData/*3:0*/ wb_mem_sel;
        CData/*0:0*/ wb_mem_we;
        CData/*0:0*/ wb_mem_stb;
        CData/*0:0*/ wb_mem_ack;
        CData/*7:0*/ rf_waddr;
        CData/*7:0*/ rf_wdata;
        CData/*0:0*/ rf_wen;
        CData/*7:0*/ rf_raddr;
        CData/*7:0*/ rf_rdata;
        CData/*0:0*/ rf_ren;
        CData/*0:0*/ rf_mem_if__DOT__i_clk;
        CData/*0:0*/ rf_mem_if__DOT__i_rst;
        CData/*7:0*/ rf_mem_if__DOT__i_waddr;
        CData/*7:0*/ rf_mem_if__DOT__i_wdata;
        CData/*0:0*/ rf_mem_if__DOT__i_wen;
        CData/*7:0*/ rf_mem_if__DOT__i_raddr;
        CData/*7:0*/ rf_mem_if__DOT__o_rdata;
        CData/*0:0*/ rf_mem_if__DOT__i_ren;
        CData/*7:0*/ rf_mem_if__DOT__o_sram_wdata;
        CData/*0:0*/ rf_mem_if__DOT__o_sram_wen;
        CData/*7:0*/ rf_mem_if__DOT__i_sram_rdata;
        CData/*0:0*/ rf_mem_if__DOT__o_sram_ren;
        CData/*6:0*/ rf_mem_if__DOT__i_wb_adr;
        CData/*3:0*/ rf_mem_if__DOT__i_wb_sel;
        CData/*0:0*/ rf_mem_if__DOT__i_wb_we;
        CData/*0:0*/ rf_mem_if__DOT__i_wb_stb;
        CData/*0:0*/ rf_mem_if__DOT__o_wb_ack;
        CData/*1:0*/ rf_mem_if__DOT__bsel;
        CData/*0:0*/ rf_mem_if__DOT__wb_en;
        CData/*0:0*/ rf_mem_if__DOT__wb_we;
        CData/*0:0*/ rf_mem_if__DOT__regzero;
        CData/*0:0*/ servile__DOT__i_clk;
        CData/*0:0*/ servile__DOT__i_rst;
        CData/*0:0*/ servile__DOT__i_timer_irq;
        CData/*3:0*/ servile__DOT__o_wb_mem_sel;
        CData/*0:0*/ servile__DOT__o_wb_mem_we;
        CData/*0:0*/ servile__DOT__o_wb_mem_stb;
        CData/*0:0*/ servile__DOT__i_wb_mem_ack;
        CData/*3:0*/ servile__DOT__o_wb_ext_sel;
        CData/*0:0*/ servile__DOT__o_wb_ext_we;
        CData/*0:0*/ servile__DOT__o_wb_ext_stb;
        CData/*0:0*/ servile__DOT__i_wb_ext_ack;
        CData/*7:0*/ servile__DOT__o_rf_waddr;
        CData/*7:0*/ servile__DOT__o_rf_wdata;
        CData/*0:0*/ servile__DOT__o_rf_wen;
        CData/*7:0*/ servile__DOT__o_rf_raddr;
        CData/*7:0*/ servile__DOT__i_rf_rdata;
        CData/*0:0*/ servile__DOT__o_rf_ren;
        CData/*0:0*/ servile__DOT__wb_ibus_stb;
        CData/*0:0*/ servile__DOT__wb_ibus_ack;
        CData/*3:0*/ servile__DOT__wb_dbus_sel;
        CData/*0:0*/ servile__DOT__wb_dbus_we;
        CData/*0:0*/ servile__DOT__wb_dbus_stb;
    };
    struct {
        CData/*0:0*/ servile__DOT__wb_dbus_ack;
        CData/*3:0*/ servile__DOT__wb_dmem_sel;
        CData/*0:0*/ servile__DOT__wb_dmem_we;
        CData/*0:0*/ servile__DOT__wb_dmem_stb;
        CData/*0:0*/ servile__DOT__wb_dmem_ack;
        CData/*0:0*/ servile__DOT__rf_wreq;
        CData/*0:0*/ servile__DOT__rf_rreq;
        CData/*5:0*/ servile__DOT__wreg0;
        CData/*5:0*/ servile__DOT__wreg1;
        CData/*0:0*/ servile__DOT__wen0;
        CData/*0:0*/ servile__DOT__wen1;
        CData/*0:0*/ servile__DOT__wdata0;
        CData/*0:0*/ servile__DOT__wdata1;
        CData/*5:0*/ servile__DOT__rreg0;
        CData/*5:0*/ servile__DOT__rreg1;
        CData/*0:0*/ servile__DOT__rf_ready;
        CData/*0:0*/ servile__DOT__rdata0;
        CData/*0:0*/ servile__DOT__rdata1;
        CData/*2:0*/ servile__DOT__mdu_op;
        CData/*0:0*/ servile__DOT__mdu_valid;
        CData/*0:0*/ servile__DOT__mdu_ready;
        CData/*0:0*/ servile__DOT__mux__DOT__i_clk;
        CData/*0:0*/ servile__DOT__mux__DOT__i_rst;
        CData/*3:0*/ servile__DOT__mux__DOT__i_wb_cpu_sel;
        CData/*0:0*/ servile__DOT__mux__DOT__i_wb_cpu_we;
        CData/*0:0*/ servile__DOT__mux__DOT__i_wb_cpu_stb;
        CData/*0:0*/ servile__DOT__mux__DOT__o_wb_cpu_ack;
        CData/*3:0*/ servile__DOT__mux__DOT__o_wb_mem_sel;
        CData/*0:0*/ servile__DOT__mux__DOT__o_wb_mem_we;
        CData/*0:0*/ servile__DOT__mux__DOT__o_wb_mem_stb;
        CData/*0:0*/ servile__DOT__mux__DOT__i_wb_mem_ack;
        CData/*3:0*/ servile__DOT__mux__DOT__o_wb_ext_sel;
        CData/*0:0*/ servile__DOT__mux__DOT__o_wb_ext_we;
        CData/*0:0*/ servile__DOT__mux__DOT__o_wb_ext_stb;
        CData/*0:0*/ servile__DOT__mux__DOT__i_wb_ext_ack;
        CData/*0:0*/ servile__DOT__mux__DOT__sig_en;
        CData/*0:0*/ servile__DOT__mux__DOT__halt_en;
        CData/*0:0*/ servile__DOT__mux__DOT__sim_ack;
        CData/*0:0*/ servile__DOT__mux__DOT__ext;
        CData/*0:0*/ servile__DOT__mux__DOT____VdfgRegularize_h6c257bca_0_0;
        CData/*3:0*/ servile__DOT__arbiter__DOT__i_wb_cpu_dbus_sel;
        CData/*0:0*/ servile__DOT__arbiter__DOT__i_wb_cpu_dbus_we;
        CData/*0:0*/ servile__DOT__arbiter__DOT__i_wb_cpu_dbus_stb;
        CData/*0:0*/ servile__DOT__arbiter__DOT__o_wb_cpu_dbus_ack;
        CData/*0:0*/ servile__DOT__arbiter__DOT__i_wb_cpu_ibus_stb;
        CData/*0:0*/ servile__DOT__arbiter__DOT__o_wb_cpu_ibus_ack;
        CData/*3:0*/ servile__DOT__arbiter__DOT__o_wb_mem_sel;
        CData/*0:0*/ servile__DOT__arbiter__DOT__o_wb_mem_we;
        CData/*0:0*/ servile__DOT__arbiter__DOT__o_wb_mem_stb;
        CData/*0:0*/ servile__DOT__arbiter__DOT__i_wb_mem_ack;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__i_clk;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__i_rst;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__i_wreq;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__i_rreq;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__o_ready;
        CData/*5:0*/ servile__DOT__rf_ram_if__DOT__i_wreg0;
        CData/*5:0*/ servile__DOT__rf_ram_if__DOT__i_wreg1;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__i_wen0;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__i_wen1;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__i_wdata0;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__i_wdata1;
        CData/*5:0*/ servile__DOT__rf_ram_if__DOT__i_rreg0;
        CData/*5:0*/ servile__DOT__rf_ram_if__DOT__i_rreg1;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__o_rdata0;
    };
    struct {
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__o_rdata1;
        CData/*7:0*/ servile__DOT__rf_ram_if__DOT__o_waddr;
        CData/*7:0*/ servile__DOT__rf_ram_if__DOT__o_wdata;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__o_wen;
        CData/*7:0*/ servile__DOT__rf_ram_if__DOT__o_raddr;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__o_ren;
        CData/*7:0*/ servile__DOT__rf_ram_if__DOT__i_rdata;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__rgnt;
        CData/*4:0*/ servile__DOT__rf_ram_if__DOT__rcnt;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__rtrig1;
        CData/*4:0*/ servile__DOT__rf_ram_if__DOT__wcnt;
        CData/*7:0*/ servile__DOT__rf_ram_if__DOT__wdata0_r;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__wen0_r;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__wen1_r;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__wtrig0;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__wtrig1;
        CData/*5:0*/ servile__DOT__rf_ram_if__DOT__wreg;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__rtrig0;
        CData/*5:0*/ servile__DOT__rf_ram_if__DOT__rreg;
        CData/*7:0*/ servile__DOT__rf_ram_if__DOT__rdata0;
        CData/*6:0*/ servile__DOT__rf_ram_if__DOT__rdata1;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__rgate;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__rreq_r;
        CData/*0:0*/ servile__DOT__rf_ram_if__DOT__gen_wtrig_ratio_neq_2__DOT__wtrig0_r;
        CData/*0:0*/ servile__DOT__cpu__DOT__clk;
        CData/*0:0*/ servile__DOT__cpu__DOT__i_rst;
        CData/*0:0*/ servile__DOT__cpu__DOT__i_timer_irq;
        CData/*0:0*/ servile__DOT__cpu__DOT__o_rf_rreq;
        CData/*0:0*/ servile__DOT__cpu__DOT__o_rf_wreq;
        CData/*0:0*/ servile__DOT__cpu__DOT__i_rf_ready;
        CData/*5:0*/ servile__DOT__cpu__DOT__o_wreg0;
        CData/*5:0*/ servile__DOT__cpu__DOT__o_wreg1;
        CData/*0:0*/ servile__DOT__cpu__DOT__o_wen0;
        CData/*0:0*/ servile__DOT__cpu__DOT__o_wen1;
        CData/*0:0*/ servile__DOT__cpu__DOT__o_wdata0;
        CData/*0:0*/ servile__DOT__cpu__DOT__o_wdata1;
        CData/*5:0*/ servile__DOT__cpu__DOT__o_rreg0;
        CData/*5:0*/ servile__DOT__cpu__DOT__o_rreg1;
        CData/*0:0*/ servile__DOT__cpu__DOT__i_rdata0;
        CData/*0:0*/ servile__DOT__cpu__DOT__i_rdata1;
        CData/*0:0*/ servile__DOT__cpu__DOT__o_ibus_cyc;
        CData/*0:0*/ servile__DOT__cpu__DOT__i_ibus_ack;
        CData/*3:0*/ servile__DOT__cpu__DOT__o_dbus_sel;
        CData/*0:0*/ servile__DOT__cpu__DOT__o_dbus_we;
        CData/*0:0*/ servile__DOT__cpu__DOT__o_dbus_cyc;
        CData/*0:0*/ servile__DOT__cpu__DOT__i_dbus_ack;
        CData/*2:0*/ servile__DOT__cpu__DOT__o_ext_funct3;
        CData/*0:0*/ servile__DOT__cpu__DOT__i_ext_ready;
        CData/*0:0*/ servile__DOT__cpu__DOT__o_mdu_valid;
        CData/*4:0*/ servile__DOT__cpu__DOT__rd_addr;
        CData/*4:0*/ servile__DOT__cpu__DOT__rs1_addr;
        CData/*4:0*/ servile__DOT__cpu__DOT__rs2_addr;
        CData/*3:0*/ servile__DOT__cpu__DOT__immdec_ctrl;
        CData/*3:0*/ servile__DOT__cpu__DOT__immdec_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__sh_right;
        CData/*0:0*/ servile__DOT__cpu__DOT__bne_or_bge;
        CData/*0:0*/ servile__DOT__cpu__DOT__cond_branch;
        CData/*0:0*/ servile__DOT__cpu__DOT__two_stage_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__e_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__ebreak;
        CData/*0:0*/ servile__DOT__cpu__DOT__branch_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__shift_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__rd_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__mdu_op;
    };
    struct {
        CData/*0:0*/ servile__DOT__cpu__DOT__rd_alu_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__rd_csr_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__rd_mem_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl_rd;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu_rd;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_rd;
        CData/*0:0*/ servile__DOT__cpu__DOT__csr_rd;
        CData/*0:0*/ servile__DOT__cpu__DOT__mtval_pc;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl_pc_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__jump;
        CData/*0:0*/ servile__DOT__cpu__DOT__jal_or_jalr;
        CData/*0:0*/ servile__DOT__cpu__DOT__utype;
        CData/*0:0*/ servile__DOT__cpu__DOT__mret;
        CData/*0:0*/ servile__DOT__cpu__DOT__imm;
        CData/*0:0*/ servile__DOT__cpu__DOT__trap;
        CData/*0:0*/ servile__DOT__cpu__DOT__pc_rel;
        CData/*0:0*/ servile__DOT__cpu__DOT__iscomp;
        CData/*0:0*/ servile__DOT__cpu__DOT__init;
        CData/*0:0*/ servile__DOT__cpu__DOT__cnt_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__cnt0to3;
        CData/*0:0*/ servile__DOT__cpu__DOT__cnt12to31;
        CData/*0:0*/ servile__DOT__cpu__DOT__cnt0;
        CData/*0:0*/ servile__DOT__cpu__DOT__cnt1;
        CData/*0:0*/ servile__DOT__cpu__DOT__cnt2;
        CData/*0:0*/ servile__DOT__cpu__DOT__cnt3;
        CData/*0:0*/ servile__DOT__cpu__DOT__cnt7;
        CData/*0:0*/ servile__DOT__cpu__DOT__cnt11;
        CData/*0:0*/ servile__DOT__cpu__DOT__cnt12;
        CData/*0:0*/ servile__DOT__cpu__DOT__cnt_done;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg_sh_signed;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg_rs1_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg_imm_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg_clr_lsb;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg_q;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2_q;
        CData/*0:0*/ servile__DOT__cpu__DOT__dbus_ack;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu_sub;
        CData/*1:0*/ servile__DOT__cpu__DOT__alu_bool_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu_cmp_eq;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu_cmp_sig;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu_cmp;
        CData/*2:0*/ servile__DOT__cpu__DOT__alu_rd_sel;
        CData/*0:0*/ servile__DOT__cpu__DOT__rs1;
        CData/*0:0*/ servile__DOT__cpu__DOT__rs2;
        CData/*0:0*/ servile__DOT__cpu__DOT__rd_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__op_b;
        CData/*0:0*/ servile__DOT__cpu__DOT__op_b_sel;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_signed;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_word;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_half;
        CData/*1:0*/ servile__DOT__cpu__DOT__mem_bytecnt;
        CData/*0:0*/ servile__DOT__cpu__DOT__sh_done;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_misalign;
        CData/*0:0*/ servile__DOT__cpu__DOT__bad_pc;
        CData/*0:0*/ servile__DOT__cpu__DOT__csr_mstatus_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__csr_mie_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__csr_mcause_en;
        CData/*1:0*/ servile__DOT__cpu__DOT__csr_source;
        CData/*0:0*/ servile__DOT__cpu__DOT__csr_imm;
        CData/*0:0*/ servile__DOT__cpu__DOT__csr_d_sel;
        CData/*0:0*/ servile__DOT__cpu__DOT__csr_en;
        CData/*1:0*/ servile__DOT__cpu__DOT__csr_addr;
        CData/*0:0*/ servile__DOT__cpu__DOT__csr_pc;
    };
    struct {
        CData/*0:0*/ servile__DOT__cpu__DOT__csr_imm_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__csr_in;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_csr_out;
        CData/*0:0*/ servile__DOT__cpu__DOT__dbus_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__new_irq;
        CData/*1:0*/ servile__DOT__cpu__DOT__lsb;
        CData/*0:0*/ servile__DOT__cpu__DOT__wb_ibus_cyc;
        CData/*0:0*/ servile__DOT__cpu__DOT__wb_ibus_ack;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_clk;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_rst;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_new_irq;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_alu_cmp;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_init;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_cnt_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_cnt0to3;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_cnt12to31;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_cnt0;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_cnt1;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_cnt2;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_cnt3;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_cnt7;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_cnt11;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_cnt12;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_cnt_done;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_bufreg_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_ctrl_pc_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_ctrl_jump;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_ctrl_trap;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_ctrl_misalign;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_sh_done;
        CData/*1:0*/ servile__DOT__cpu__DOT__state__DOT__o_mem_bytecnt;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_mem_misalign;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_bne_or_bge;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_cond_branch;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_dbus_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_two_stage_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_branch_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_shift_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_sh_right;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_alu_rd_sel1;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_rd_alu_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_e_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_rd_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_mdu_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_mdu_valid;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_mdu_ready;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_dbus_cyc;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_dbus_ack;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_ibus_cyc;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_ibus_ack;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_rf_rreq;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_rf_wreq;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__i_rf_ready;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__o_rf_rd_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__init_done;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__misalign_trap_sync;
        CData/*2:0*/ servile__DOT__cpu__DOT__state__DOT__o_cnt;
        CData/*3:0*/ servile__DOT__cpu__DOT__state__DOT__cnt_r;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__ibus_cyc;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__take_branch;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__last_init;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__trap_pending;
        CData/*3:0*/ servile__DOT__cpu__DOT__state__DOT__gen_cnt_w_eq_1__DOT__cnt_lsb;
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__gen_csr__DOT__misalign_trap_sync_r;
    };
    struct {
        CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT____VdfgRegularize_h53222178_0_2;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__clk;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__i_wb_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_sh_right;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_bne_or_bge;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_cond_branch;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_e_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_ebreak;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_branch_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_shift_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_rd_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_two_stage_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_dbus_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_mdu_op;
        CData/*2:0*/ servile__DOT__cpu__DOT__decode__DOT__o_ext_funct3;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_bufreg_rs1_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_bufreg_imm_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_bufreg_clr_lsb;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_bufreg_sh_signed;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_ctrl_jal_or_jalr;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_ctrl_utype;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_ctrl_pc_rel;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_ctrl_mret;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_alu_sub;
        CData/*1:0*/ servile__DOT__cpu__DOT__decode__DOT__o_alu_bool_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_alu_cmp_eq;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_alu_cmp_sig;
        CData/*2:0*/ servile__DOT__cpu__DOT__decode__DOT__o_alu_rd_sel;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_mem_signed;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_mem_word;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_mem_half;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_mem_cmd;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_csr_en;
        CData/*1:0*/ servile__DOT__cpu__DOT__decode__DOT__o_csr_addr;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_csr_mstatus_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_csr_mie_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_csr_mcause_en;
        CData/*1:0*/ servile__DOT__cpu__DOT__decode__DOT__o_csr_source;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_csr_d_sel;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_csr_imm_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_mtval_pc;
        CData/*3:0*/ servile__DOT__cpu__DOT__decode__DOT__o_immdec_ctrl;
        CData/*3:0*/ servile__DOT__cpu__DOT__decode__DOT__o_immdec_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_op_b_source;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_rd_mem_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_rd_csr_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__o_rd_alu_en;
        CData/*4:0*/ servile__DOT__cpu__DOT__decode__DOT__opcode;
        CData/*2:0*/ servile__DOT__cpu__DOT__decode__DOT__funct3;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__op20;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__op21;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__op22;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__op26;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__imm25;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__imm30;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_mdu_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_two_stage_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_shift_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_branch_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_dbus_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_mtval_pc;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_mem_word;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_rd_alu_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_rd_mem_en;
    };
    struct {
        CData/*2:0*/ servile__DOT__cpu__DOT__decode__DOT__co_ext_funct3;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_bufreg_rs1_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_bufreg_imm_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_bufreg_clr_lsb;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_cond_branch;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_ctrl_utype;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_ctrl_jal_or_jalr;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_ctrl_pc_rel;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_rd_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_sh_right;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_bne_or_bge;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__csr_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_ebreak;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_ctrl_mret;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_e_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_bufreg_sh_signed;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_alu_sub;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__csr_valid;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_rd_csr_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_csr_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_csr_mstatus_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_csr_mie_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_csr_mcause_en;
        CData/*1:0*/ servile__DOT__cpu__DOT__decode__DOT__co_csr_source;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_csr_d_sel;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_csr_imm_en;
        CData/*1:0*/ servile__DOT__cpu__DOT__decode__DOT__co_csr_addr;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_alu_cmp_eq;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_alu_cmp_sig;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_mem_cmd;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_mem_signed;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_mem_half;
        CData/*1:0*/ servile__DOT__cpu__DOT__decode__DOT__co_alu_bool_op;
        CData/*3:0*/ servile__DOT__cpu__DOT__decode__DOT__co_immdec_ctrl;
        CData/*3:0*/ servile__DOT__cpu__DOT__decode__DOT__co_immdec_en;
        CData/*2:0*/ servile__DOT__cpu__DOT__decode__DOT__co_alu_rd_sel;
        CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__co_op_b_source;
        CData/*0:0*/ servile__DOT__cpu__DOT__immdec__DOT__i_clk;
        CData/*0:0*/ servile__DOT__cpu__DOT__immdec__DOT__i_cnt_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__immdec__DOT__i_cnt_done;
        CData/*3:0*/ servile__DOT__cpu__DOT__immdec__DOT__i_immdec_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__immdec__DOT__i_csr_imm_en;
        CData/*3:0*/ servile__DOT__cpu__DOT__immdec__DOT__i_ctrl;
        CData/*4:0*/ servile__DOT__cpu__DOT__immdec__DOT__o_rd_addr;
        CData/*4:0*/ servile__DOT__cpu__DOT__immdec__DOT__o_rs1_addr;
        CData/*4:0*/ servile__DOT__cpu__DOT__immdec__DOT__o_rs2_addr;
        CData/*0:0*/ servile__DOT__cpu__DOT__immdec__DOT__o_csr_imm;
        CData/*0:0*/ servile__DOT__cpu__DOT__immdec__DOT__o_imm;
        CData/*0:0*/ servile__DOT__cpu__DOT__immdec__DOT__i_wb_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__immdec__DOT__gen_immdec_w_eq_1__DOT__imm31;
        CData/*0:0*/ servile__DOT__cpu__DOT__immdec__DOT__gen_immdec_w_eq_1__DOT__imm7;
        CData/*5:0*/ servile__DOT__cpu__DOT__immdec__DOT__gen_immdec_w_eq_1__DOT__imm30_25;
        CData/*4:0*/ servile__DOT__cpu__DOT__immdec__DOT__gen_immdec_w_eq_1__DOT__imm24_20;
        CData/*4:0*/ servile__DOT__cpu__DOT__immdec__DOT__gen_immdec_w_eq_1__DOT__imm11_7;
        CData/*0:0*/ servile__DOT__cpu__DOT__immdec__DOT__gen_immdec_w_eq_1__DOT__signbit;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_clk;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_cnt0;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_cnt1;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_cnt_done;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_init;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_mdu_op;
        CData/*1:0*/ servile__DOT__cpu__DOT__bufreg__DOT__o_lsb;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_rs1_en;
    };
    struct {
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_imm_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_clr_lsb;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_shift_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_right_shift_op;
        CData/*2:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_shamt;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_sh_signed;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_rs1;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__i_imm;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__o_q;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__c;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__q;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__c_r;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__clr_lsb;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_clk;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_init;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_cnt7;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_cnt_done;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_sh_right;
        CData/*1:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_lsb;
        CData/*1:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_bytecnt;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__o_sh_done;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_op_b_sel;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_shift_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_rs2;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_imm;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__o_op_b;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__o_q;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_load;
        CData/*7:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__dhi;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__byte_valid;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__shift_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__cnt_en;
        CData/*7:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__cnt_next;
        CData/*7:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__dat_shamt;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__clk;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_rst;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_pc_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_cnt12to31;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_cnt0;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_cnt1;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_cnt2;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_jump;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_jal_or_jalr;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_utype;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_pc_rel;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_trap;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_iscomp;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_imm;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_buf;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__i_csr_pc;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__o_rd;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__o_bad_pc;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__pc_plus_4;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__pc_plus_4_cy;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__pc_plus_4_cy_r;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__pc_plus_4_cy_r_w;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__pc_plus_offset;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__pc_plus_offset_cy;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__pc_plus_offset_cy_r;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__pc_plus_offset_cy_r_w;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__pc_plus_offset_aligned;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__plus_4;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__pc;
    };
    struct {
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__new_pc;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__offset_a;
        CData/*0:0*/ servile__DOT__cpu__DOT__ctrl__DOT__offset_b;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__clk;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__i_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__i_cnt0;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__o_cmp;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__i_sub;
        CData/*1:0*/ servile__DOT__cpu__DOT__alu__DOT__i_bool_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__i_cmp_eq;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__i_cmp_sig;
        CData/*2:0*/ servile__DOT__cpu__DOT__alu__DOT__i_rd_sel;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__i_rs1;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__i_op_b;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__i_buf;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__o_rd;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__result_add;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__result_slt;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__cmp_r;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__add_cy;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__add_cy_r;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__rs1_sx;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__op_b_sx;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__add_b;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__result_lt;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__result_eq;
        CData/*0:0*/ servile__DOT__cpu__DOT__alu__DOT__result_bool;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_cnt_en;
        CData/*5:0*/ servile__DOT__cpu__DOT__rf_if__DOT__o_wreg0;
        CData/*5:0*/ servile__DOT__cpu__DOT__rf_if__DOT__o_wreg1;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__o_wen0;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__o_wen1;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__o_wdata0;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__o_wdata1;
        CData/*5:0*/ servile__DOT__cpu__DOT__rf_if__DOT__o_rreg0;
        CData/*5:0*/ servile__DOT__cpu__DOT__rf_if__DOT__o_rreg1;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_rdata0;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_rdata1;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_trap;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_mret;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_mepc;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_mtval_pc;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_bufreg_q;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_bad_pc;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__o_csr_pc;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_csr_en;
        CData/*1:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_csr_addr;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_csr;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__o_csr;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_rd_wen;
        CData/*4:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_rd_waddr;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_ctrl_rd;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_alu_rd;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_rd_alu_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_csr_rd;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_rd_csr_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_mem_rd;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_rd_mem_en;
        CData/*4:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_rs1_raddr;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__o_rs1;
        CData/*4:0*/ servile__DOT__cpu__DOT__rf_if__DOT__i_rs2_raddr;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__o_rs2;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__rd_wen;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__gen_csr__DOT__rd;
    };
    struct {
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__gen_csr__DOT__mtval;
        CData/*0:0*/ servile__DOT__cpu__DOT__rf_if__DOT__gen_csr__DOT__sel_rs2;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_if__DOT__i_clk;
        CData/*1:0*/ servile__DOT__cpu__DOT__mem_if__DOT__i_bytecnt;
        CData/*1:0*/ servile__DOT__cpu__DOT__mem_if__DOT__i_lsb;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_if__DOT__o_misalign;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_if__DOT__i_signed;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_if__DOT__i_word;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_if__DOT__i_half;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_if__DOT__i_mdu_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_if__DOT__i_bufreg2_q;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_if__DOT__o_rd;
        CData/*3:0*/ servile__DOT__cpu__DOT__mem_if__DOT__o_wb_sel;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_if__DOT__signbit;
        CData/*0:0*/ servile__DOT__cpu__DOT__mem_if__DOT__dat_valid;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_clk;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_rst;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_trig_irq;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_cnt0to3;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_cnt3;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_cnt7;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_cnt11;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_cnt12;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_cnt_done;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_mem_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_mtip;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_trap;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__o_new_irq;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_e_op;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_ebreak;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_mem_cmd;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_mstatus_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_mie_en;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_mcause_en;
        CData/*1:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_csr_source;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_mret;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_csr_d_sel;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_rf_csr_out;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__o_csr_in;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_csr_imm;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_rs1;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__o_q;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__mstatus_mie;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__mstatus_mpie;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__mie_mtie;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__mcause31;
        CData/*3:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__mcause3_0;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__mcause;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__csr_in;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__csr_out;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__timer_irq_r;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__d;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__mstatus;
        CData/*0:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__timer_irq;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_0;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_1;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_2;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_3;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_4;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_5;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_6;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_7;
        VL_OUT16(o_sram_waddr,8,0);
    };
    struct {
        VL_OUT16(o_sram_raddr,8,0);
        SData/*8:0*/ rf_mem_if__DOT__o_sram_waddr;
        SData/*8:0*/ rf_mem_if__DOT__o_sram_raddr;
        SData/*8:0*/ rf_mem_if__DOT__rf_waddr;
        SData/*8:0*/ rf_mem_if__DOT__rf_raddr;
        SData/*8:0*/ rf_mem_if__DOT____VdfgRegularize_h04f68ef0_0_0;
        SData/*8:0*/ servile__DOT__rf_ram_if__DOT__wdata1_r;
        SData/*8:0*/ servile__DOT__cpu__DOT__immdec__DOT__gen_immdec_w_eq_1__DOT__imm19_12_20;
        VL_OUT(o_wb_adr,31,0);
        VL_OUT(o_wb_dat,31,0);
        VL_IN(i_wb_rdt,31,0);
        IData/*31:0*/ wb_mem_adr;
        IData/*31:0*/ wb_mem_dat;
        IData/*31:0*/ wb_mem_rdt;
        IData/*31:0*/ rf_mem_if__DOT__i_wb_dat;
        IData/*31:0*/ rf_mem_if__DOT__o_wb_rdt;
        IData/*23:0*/ rf_mem_if__DOT__wb_rdt;
        IData/*31:0*/ servile__DOT__o_wb_mem_adr;
        IData/*31:0*/ servile__DOT__o_wb_mem_dat;
        IData/*31:0*/ servile__DOT__i_wb_mem_rdt;
        IData/*31:0*/ servile__DOT__o_wb_ext_adr;
        IData/*31:0*/ servile__DOT__o_wb_ext_dat;
        IData/*31:0*/ servile__DOT__i_wb_ext_rdt;
        IData/*31:0*/ servile__DOT__wb_ibus_adr;
        IData/*31:0*/ servile__DOT__wb_ibus_rdt;
        IData/*31:0*/ servile__DOT__wb_dbus_adr;
        IData/*31:0*/ servile__DOT__wb_dbus_dat;
        IData/*31:0*/ servile__DOT__wb_dbus_rdt;
        IData/*31:0*/ servile__DOT__wb_dmem_adr;
        IData/*31:0*/ servile__DOT__wb_dmem_dat;
        IData/*31:0*/ servile__DOT__wb_dmem_rdt;
        IData/*31:0*/ servile__DOT__mdu_rs1;
        IData/*31:0*/ servile__DOT__mdu_rs2;
        IData/*31:0*/ servile__DOT__mdu_rd;
        IData/*31:0*/ servile__DOT__mux__DOT__i_wb_cpu_adr;
        IData/*31:0*/ servile__DOT__mux__DOT__i_wb_cpu_dat;
        IData/*31:0*/ servile__DOT__mux__DOT__o_wb_cpu_rdt;
        IData/*31:0*/ servile__DOT__mux__DOT__o_wb_mem_adr;
        IData/*31:0*/ servile__DOT__mux__DOT__o_wb_mem_dat;
        IData/*31:0*/ servile__DOT__mux__DOT__i_wb_mem_rdt;
        IData/*31:0*/ servile__DOT__mux__DOT__o_wb_ext_adr;
        IData/*31:0*/ servile__DOT__mux__DOT__o_wb_ext_dat;
        IData/*31:0*/ servile__DOT__mux__DOT__i_wb_ext_rdt;
        IData/*31:0*/ servile__DOT__arbiter__DOT__i_wb_cpu_dbus_adr;
        IData/*31:0*/ servile__DOT__arbiter__DOT__i_wb_cpu_dbus_dat;
        IData/*31:0*/ servile__DOT__arbiter__DOT__o_wb_cpu_dbus_rdt;
        IData/*31:0*/ servile__DOT__arbiter__DOT__i_wb_cpu_ibus_adr;
        IData/*31:0*/ servile__DOT__arbiter__DOT__o_wb_cpu_ibus_rdt;
        IData/*31:0*/ servile__DOT__arbiter__DOT__o_wb_mem_adr;
        IData/*31:0*/ servile__DOT__arbiter__DOT__o_wb_mem_dat;
        IData/*31:0*/ servile__DOT__arbiter__DOT__i_wb_mem_rdt;
        IData/*31:0*/ servile__DOT__cpu__DOT__o_ibus_adr;
        IData/*31:0*/ servile__DOT__cpu__DOT__i_ibus_rdt;
        IData/*31:0*/ servile__DOT__cpu__DOT__o_dbus_adr;
        IData/*31:0*/ servile__DOT__cpu__DOT__o_dbus_dat;
        IData/*31:0*/ servile__DOT__cpu__DOT__i_dbus_rdt;
        IData/*31:0*/ servile__DOT__cpu__DOT__i_ext_rd;
        IData/*31:0*/ servile__DOT__cpu__DOT__o_ext_rs1;
        IData/*31:0*/ servile__DOT__cpu__DOT__o_ext_rs2;
        IData/*31:0*/ servile__DOT__cpu__DOT__dbus_rdt;
        IData/*31:0*/ servile__DOT__cpu__DOT__i_wb_rdt;
        IData/*31:0*/ servile__DOT__cpu__DOT__wb_ibus_adr;
        IData/*31:0*/ servile__DOT__cpu__DOT__wb_ibus_rdt;
        IData/*29:0*/ servile__DOT__cpu__DOT__decode__DOT__i_wb_rdt;
    };
    struct {
        IData/*24:0*/ servile__DOT__cpu__DOT__immdec__DOT__i_wb_rdt;
        IData/*31:0*/ servile__DOT__cpu__DOT__bufreg__DOT__o_dbus_adr;
        IData/*31:0*/ servile__DOT__cpu__DOT__bufreg__DOT__o_ext_rs1;
        IData/*31:0*/ servile__DOT__cpu__DOT__bufreg__DOT__data;
        IData/*31:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__o_dat;
        IData/*31:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__i_dat;
        IData/*23:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__dlo;
        IData/*31:0*/ servile__DOT__cpu__DOT__ctrl__DOT__o_ibus_adr;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr CData/*0:0*/ servile__DOT__sim = 0U;
    static constexpr CData/*0:0*/ servile__DOT__debug = 0U;
    static constexpr CData/*0:0*/ servile__DOT__with_c = 0U;
    static constexpr CData/*0:0*/ servile__DOT__with_csr = 1U;
    static constexpr CData/*0:0*/ servile__DOT__with_mdu = 0U;
    static constexpr CData/*0:0*/ servile__DOT__mux__DOT__sim = 0U;
    static constexpr CData/*0:0*/ servile__DOT__cpu__DOT__PRE_REGISTER = 1U;
    static constexpr CData/*0:0*/ servile__DOT__cpu__DOT__DEBUG = 0U;
    static constexpr CData/*0:0*/ servile__DOT__cpu__DOT__MDU = 0U;
    static constexpr CData/*0:0*/ servile__DOT__cpu__DOT__COMPRESSED = 0U;
    static constexpr CData/*0:0*/ servile__DOT__cpu__DOT__ALIGN = 0U;
    static constexpr CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__WITH_CSR = 1U;
    static constexpr CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__ALIGN = 0U;
    static constexpr CData/*0:0*/ servile__DOT__cpu__DOT__state__DOT__MDU = 0U;
    static constexpr CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__PRE_REGISTER = 1U;
    static constexpr CData/*0:0*/ servile__DOT__cpu__DOT__decode__DOT__MDU = 0U;
    static constexpr CData/*0:0*/ servile__DOT__cpu__DOT__bufreg__DOT__MDU = 0U;
    static constexpr CData/*0:0*/ servile__DOT__cpu__DOT__mem_if__DOT__WITH_CSR = 1U;
    static constexpr CData/*1:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__CSR_SOURCE_CSR = 0U;
    static constexpr CData/*1:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__CSR_SOURCE_EXT = 1U;
    static constexpr CData/*1:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__CSR_SOURCE_SET = 2U;
    static constexpr CData/*1:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__CSR_SOURCE_CLR = 3U;
    static constexpr IData/*31:0*/ memsize = 0x00000200U;
    static constexpr IData/*31:0*/ RESET_STRATEGY = 0x4d494e49U;
    static constexpr IData/*31:0*/ WITH_CSR = 1U;
    static constexpr IData/*31:0*/ aw = 9U;
    static constexpr IData/*31:0*/ regs = 0x00000024U;
    static constexpr IData/*31:0*/ rf_width = 8U;
    static constexpr IData/*31:0*/ rf_mem_if__DOT__depth = 0x00000200U;
    static constexpr IData/*31:0*/ rf_mem_if__DOT__rf_regs = 0x00000024U;
    static constexpr IData/*31:0*/ rf_mem_if__DOT__rf_depth = 8U;
    static constexpr IData/*31:0*/ rf_mem_if__DOT__aw = 9U;
    static constexpr IData/*31:0*/ servile__DOT__width = 1U;
    static constexpr IData/*31:0*/ servile__DOT__reset_pc = 0U;
    static constexpr IData/*31:0*/ servile__DOT__reset_strategy = 0x4d494e49U;
    static constexpr IData/*31:0*/ servile__DOT__rf_width = 8U;
    static constexpr IData/*31:0*/ servile__DOT__B = 0U;
    static constexpr IData/*31:0*/ servile__DOT__regs = 0x00000024U;
    static constexpr IData/*31:0*/ servile__DOT__rf_l2d = 8U;
    static constexpr IData/*31:0*/ servile__DOT__mux__DOT__sim_sig_adr = 0x80000000U;
    static constexpr IData/*31:0*/ servile__DOT__mux__DOT__sim_halt_adr = 0x90000000U;
    static constexpr IData/*31:0*/ servile__DOT__rf_ram_if__DOT__width = 8U;
    static constexpr IData/*31:0*/ servile__DOT__rf_ram_if__DOT__W = 1U;
    static constexpr IData/*31:0*/ servile__DOT__rf_ram_if__DOT__reset_strategy = 0x4d494e49U;
    static constexpr IData/*31:0*/ servile__DOT__rf_ram_if__DOT__csr_regs = 4U;
    static constexpr IData/*31:0*/ servile__DOT__rf_ram_if__DOT__B = 0U;
    static constexpr IData/*31:0*/ servile__DOT__rf_ram_if__DOT__raw = 6U;
    static constexpr IData/*31:0*/ servile__DOT__rf_ram_if__DOT__l2w = 3U;
    static constexpr IData/*31:0*/ servile__DOT__rf_ram_if__DOT__aw = 8U;
    static constexpr IData/*31:0*/ servile__DOT__rf_ram_if__DOT__ratio = 8U;
    static constexpr IData/*31:0*/ servile__DOT__rf_ram_if__DOT__CMSB = 4U;
    static constexpr IData/*31:0*/ servile__DOT__rf_ram_if__DOT__l2r = 3U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__WITH_CSR = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__W = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__B = 0U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__RESET_STRATEGY = 0x4d494e49U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__RESET_PC = 0U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__state__DOT__RESET_STRATEGY = 0x4d494e49U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__state__DOT__W = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__immdec__DOT__SHARED_RFADDR_IMM_REGS = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__immdec__DOT__W = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__bufreg__DOT__W = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__bufreg__DOT__B = 0U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__W = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__bufreg2__DOT__B = 0U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__ctrl__DOT__RESET_STRATEGY = 0x4d494e49U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__ctrl__DOT__RESET_PC = 0U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__ctrl__DOT__WITH_CSR = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__ctrl__DOT__W = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__ctrl__DOT__B = 0U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__alu__DOT__W = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__alu__DOT__B = 0U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__rf_if__DOT__WITH_CSR = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__rf_if__DOT__W = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__rf_if__DOT__B = 0U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__mem_if__DOT__W = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__mem_if__DOT__B = 0U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__RESET_STRATEGY = 0x4d494e49U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__W = 1U;
    static constexpr IData/*31:0*/ servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__B = 0U;

    // CONSTRUCTORS
    Vtop_subservient_core() = default;
    ~Vtop_subservient_core() = default;
    void ctor(Vtop__Syms* symsp, const char* namep);
    void dtor();
    VL_UNCOPYABLE(Vtop_subservient_core);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
