// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
class Vtop_subservient_core;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:
    // CELLS
    Vtop_subservient_core* __PVT__mesh_2x2__DOT__t00__DOT__core;
    Vtop_subservient_core* __PVT__mesh_2x2__DOT__t01__DOT__core;
    Vtop_subservient_core* __PVT__mesh_2x2__DOT__t10__DOT__core;
    Vtop_subservient_core* __PVT__mesh_2x2__DOT__t11__DOT__core;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        CData/*0:0*/ mesh_2x2__DOT__clk;
        CData/*0:0*/ mesh_2x2__DOT__rst;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__clk;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__rst;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__wb_we;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__wb_stb;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__wb_ack;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__clk;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__rst;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__local_wb_we;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__local_wb_stb;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__local_wb_ack;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__my_row;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__my_col;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__north_buf;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__south_buf;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__east_buf;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__west_buf;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__north_valid;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__south_valid;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__east_valid;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__west_valid;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__is_network_send;
        CData/*0:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__is_network_recv;
        CData/*3:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__recv_sel;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__clk;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__rst;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__wb_we;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__wb_stb;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__wb_ack;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__clk;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__rst;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__local_wb_we;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__local_wb_stb;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__local_wb_ack;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__my_row;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__my_col;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__north_buf;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__south_buf;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__east_buf;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__west_buf;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__north_valid;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__south_valid;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__east_valid;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__west_valid;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__is_network_send;
        CData/*0:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__is_network_recv;
        CData/*3:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__recv_sel;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__clk;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__rst;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__wb_we;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__wb_stb;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__wb_ack;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__clk;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__rst;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__local_wb_we;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__local_wb_stb;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__local_wb_ack;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__my_row;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__my_col;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__north_buf;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__south_buf;
    };
    struct {
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__east_buf;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__west_buf;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__north_valid;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__south_valid;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__east_valid;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__west_valid;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__is_network_send;
        CData/*0:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__is_network_recv;
        CData/*3:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__recv_sel;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__clk;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__rst;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__wb_we;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__wb_stb;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__wb_ack;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__clk;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__rst;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__local_wb_we;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__local_wb_stb;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__local_wb_ack;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__my_row;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__my_col;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__north_buf;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__south_buf;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__east_buf;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__west_buf;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__north_valid;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__south_valid;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__east_valid;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__west_valid;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__is_network_send;
        CData/*0:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__is_network_recv;
        CData/*3:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__recv_sel;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__router__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__router__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__router__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t11__DOT__router__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__core__rf_mem_if__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__core__servile__DOT__rf_ram_if__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__core__servile__DOT__cpu__DOT__state__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__core__servile__DOT__cpu__DOT__decode__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__core__servile__DOT__cpu__DOT__immdec__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__core__servile__DOT__cpu__DOT__bufreg__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__core__servile__DOT__cpu__DOT__bufreg2__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__core__servile__DOT__cpu__DOT__ctrl__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__core__servile__DOT__cpu__DOT__alu__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__core__servile__DOT__cpu__DOT__mem_if__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__core__servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__core__rf_mem_if__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__core__servile__DOT__rf_ram_if__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__core__servile__DOT__cpu__DOT__state__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__core__servile__DOT__cpu__DOT__decode__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__core__servile__DOT__cpu__DOT__immdec__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__core__servile__DOT__cpu__DOT__bufreg__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__core__servile__DOT__cpu__DOT__bufreg2__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__core__servile__DOT__cpu__DOT__ctrl__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__core__servile__DOT__cpu__DOT__alu__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__core__servile__DOT__cpu__DOT__mem_if__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__core__servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__core__rf_mem_if__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__core__servile__DOT__rf_ram_if__DOT__i_clk__0;
    };
    struct {
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__core__servile__DOT__cpu__DOT__state__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__core__servile__DOT__cpu__DOT__decode__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__core__servile__DOT__cpu__DOT__immdec__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__core__servile__DOT__cpu__DOT__bufreg__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__core__servile__DOT__cpu__DOT__bufreg2__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__core__servile__DOT__cpu__DOT__ctrl__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__core__servile__DOT__cpu__DOT__alu__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__core__servile__DOT__cpu__DOT__mem_if__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__core__servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t11__DOT__core__rf_mem_if__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t11__DOT__core__servile__DOT__rf_ram_if__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t11__DOT__core__servile__DOT__cpu__DOT__state__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t11__DOT__core__servile__DOT__cpu__DOT__decode__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t11__DOT__core__servile__DOT__cpu__DOT__immdec__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t11__DOT__core__servile__DOT__cpu__DOT__bufreg__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t11__DOT__core__servile__DOT__cpu__DOT__bufreg2__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t11__DOT__core__servile__DOT__cpu__DOT__ctrl__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t11__DOT__core__servile__DOT__cpu__DOT__alu__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t11__DOT__core__servile__DOT__cpu__DOT__mem_if__DOT__i_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t11__DOT__core__servile__DOT__cpu__DOT__gen_csr__DOT__csr__DOT__i_clk__0;
        CData/*0:0*/ __VactDidInit;
        IData/*31:0*/ mesh_2x2__DOT__t00__DOT__wb_adr;
        IData/*31:0*/ mesh_2x2__DOT__t00__DOT__wb_dat_o;
        IData/*31:0*/ mesh_2x2__DOT__t00__DOT__wb_dat_i;
        IData/*31:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__local_wb_adr;
        IData/*31:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__local_wb_dat_o;
        IData/*31:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__local_wb_dat_i;
        IData/*31:0*/ mesh_2x2__DOT__t01__DOT__wb_adr;
        IData/*31:0*/ mesh_2x2__DOT__t01__DOT__wb_dat_o;
        IData/*31:0*/ mesh_2x2__DOT__t01__DOT__wb_dat_i;
        IData/*31:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__local_wb_adr;
        IData/*31:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__local_wb_dat_o;
        IData/*31:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__local_wb_dat_i;
        IData/*31:0*/ mesh_2x2__DOT__t10__DOT__wb_adr;
        IData/*31:0*/ mesh_2x2__DOT__t10__DOT__wb_dat_o;
        IData/*31:0*/ mesh_2x2__DOT__t10__DOT__wb_dat_i;
        IData/*31:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__local_wb_adr;
        IData/*31:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__local_wb_dat_o;
        IData/*31:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__local_wb_dat_i;
        IData/*31:0*/ mesh_2x2__DOT__t11__DOT__wb_adr;
        IData/*31:0*/ mesh_2x2__DOT__t11__DOT__wb_dat_o;
        IData/*31:0*/ mesh_2x2__DOT__t11__DOT__wb_dat_i;
        IData/*31:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__local_wb_adr;
        IData/*31:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__local_wb_dat_o;
        IData/*31:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__local_wb_dat_i;
        IData/*31:0*/ __VactIterCount;
        QData/*33:0*/ mesh_2x2__DOT__n00_n01;
        QData/*33:0*/ mesh_2x2__DOT__n01_n00;
        QData/*33:0*/ mesh_2x2__DOT__n10_n11;
        QData/*33:0*/ mesh_2x2__DOT__n11_n10;
        QData/*33:0*/ mesh_2x2__DOT__n00_n10;
        QData/*33:0*/ mesh_2x2__DOT__n10_n00;
        QData/*33:0*/ mesh_2x2__DOT__n01_n11;
        QData/*33:0*/ mesh_2x2__DOT__n11_n01;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__north_out;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__south_out;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__east_out;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__west_out;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__north_in;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__south_in;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__east_in;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__west_in;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__north_out;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__south_out;
    };
    struct {
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__east_out;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__west_out;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__north_in;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__south_in;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__east_in;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__west_in;
        QData/*33:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__inject_flit;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__north_out;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__south_out;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__east_out;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__west_out;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__north_in;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__south_in;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__east_in;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__west_in;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__north_out;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__south_out;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__east_out;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__west_out;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__north_in;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__south_in;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__east_in;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__west_in;
        QData/*33:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__inject_flit;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__north_out;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__south_out;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__east_out;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__west_out;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__north_in;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__south_in;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__east_in;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__west_in;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__north_out;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__south_out;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__east_out;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__west_out;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__north_in;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__south_in;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__east_in;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__west_in;
        QData/*33:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__inject_flit;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__north_out;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__south_out;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__east_out;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__west_out;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__north_in;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__south_in;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__east_in;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__west_in;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__north_out;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__south_out;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__east_out;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__west_out;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__north_in;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__south_in;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__east_in;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__west_in;
        QData/*33:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__inject_flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t00__DOT__router__DOT__route_flit__0__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t00__DOT__router__DOT__route_flit__1__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t00__DOT__router__DOT__route_flit__2__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t00__DOT__router__DOT__route_flit__3__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t00__DOT__router__DOT__route_flit__4__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t01__DOT__router__DOT__route_flit__5__flit;
    };
    struct {
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t01__DOT__router__DOT__route_flit__6__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t01__DOT__router__DOT__route_flit__7__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t01__DOT__router__DOT__route_flit__8__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t01__DOT__router__DOT__route_flit__9__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t10__DOT__router__DOT__route_flit__10__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t10__DOT__router__DOT__route_flit__11__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t10__DOT__router__DOT__route_flit__12__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t10__DOT__router__DOT__route_flit__13__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t10__DOT__router__DOT__route_flit__14__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t11__DOT__router__DOT__route_flit__15__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t11__DOT__router__DOT__route_flit__16__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t11__DOT__router__DOT__route_flit__17__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t11__DOT__router__DOT__route_flit__18__flit;
        QData/*33:0*/ __Vtask_mesh_2x2__DOT__t11__DOT__router__DOT__route_flit__19__flit;
        QData/*33:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__router__DOT__south_in__0;
        QData/*33:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__router__DOT__east_in__0;
        QData/*33:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__router__DOT__east_in__0;
        QData/*33:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__router__DOT__south_in__0;
        QData/*33:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__router__DOT__south_in__1;
        QData/*33:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__router__DOT__east_in__1;
        QData/*33:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__router__DOT__east_in__1;
        QData/*33:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__router__DOT__south_in__1;
        QData/*33:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__router__DOT__south_in__2;
        QData/*33:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t00__DOT__router__DOT__east_in__2;
        QData/*33:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t01__DOT__router__DOT__east_in__2;
        QData/*33:0*/ __Vtrigprevexpr___TOP__mesh_2x2__DOT__t10__DOT__router__DOT__south_in__2;
        VlUnpacked<QData/*63:0*/, 2> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr CData/*1:0*/ mesh_2x2__DOT__t00__DOT__TILE_ID = 0U;
    static constexpr CData/*1:0*/ mesh_2x2__DOT__t00__DOT__router__DOT__MY_ID = 0U;
    static constexpr CData/*1:0*/ mesh_2x2__DOT__t01__DOT__TILE_ID = 1U;
    static constexpr CData/*1:0*/ mesh_2x2__DOT__t01__DOT__router__DOT__MY_ID = 1U;
    static constexpr CData/*1:0*/ mesh_2x2__DOT__t10__DOT__TILE_ID = 2U;
    static constexpr CData/*1:0*/ mesh_2x2__DOT__t10__DOT__router__DOT__MY_ID = 2U;
    static constexpr CData/*1:0*/ mesh_2x2__DOT__t11__DOT__TILE_ID = 3U;
    static constexpr CData/*1:0*/ mesh_2x2__DOT__t11__DOT__router__DOT__MY_ID = 3U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
