# meta:
#   version: 3
#   flow: Chip
#   substituting_steps:

#     # Disable KLayout DRC
#     #KLayout.DRC: null
#     #Checker.KLayoutDRC: null

#     # Disable KLayout antenna check
#     #KLayout.Antenna: null
#     #Checker.KLayoutAntenna: null

#     # Disable KLayout density check
#     #KLayout.Density: null
#     #Checker.KLayoutDensity: null

#     # Save time during development
#     # Enable for sign-off
#     #OpenROAD.IRDropReport: null
#     #Magic.DRC: null
#     #Checker.MagicDRC: null
#     #KLayout.XOR: null
#     #Netgen.LVS: null
#     #Checker.LVS: null

# DESIGN_NAME: chip_top
# VERILOG_FILES:
# - dir::../src/chip_top.sv
# - dir::../src/chip_core.sv
# - dir::../src/boot_loader.v
# - dir::../src/mesh_router.v
# - dir::../src/mesh_tile.v
# - dir::../src/mesh_3x3.v
# - dir::../src/subservient_core.v
# - dir::../src/serv/rtl/serv_aligner.v
# - dir::../src/serv/rtl/serv_alu.v
# - dir::../src/serv/rtl/serv_bufreg.v
# - dir::../src/serv/rtl/serv_bufreg2.v
# - dir::../src/serv/rtl/serv_compdec.v
# - dir::../src/serv/rtl/serv_csr.v
# - dir::../src/serv/rtl/serv_ctrl.v
# - dir::../src/serv/rtl/serv_debug.v
# - dir::../src/serv/rtl/serv_decode.v
# - dir::../src/serv/rtl/serv_immdec.v
# - dir::../src/serv/rtl/serv_mem_if.v
# - dir::../src/serv/rtl/serv_rf_if.v
# - dir::../src/serv/rtl/serv_rf_ram_if.v
# - dir::../src/serv/rtl/serv_rf_ram.v
# - dir::../src/serv/rtl/serv_rf_top.v
# - dir::../src/serv/rtl/serv_state.v
# - dir::../src/serv/rtl/serv_synth_wrapper.v
# - dir::../src/serv/rtl/serv_top.v
# - dir::../src/serv/servile/servile_arbiter.v
# - dir::../src/serv/servile/servile_mux.v
# - dir::../src/serv/servile/servile_rf_mem_if.v
# - dir::../src/serv/servile/servile.v
# - dir::../src/subservient/rtl/subservient_debug_switch.v
# - dir::../src/subservient/rtl/subservient_fpga.v
# - dir::../src/subservient/rtl/subservient_generic_ram.v
# - dir::../src/subservient/rtl/subservient_gpio.v
# - dir::../src/subservient/rtl/subservient_nexys_a7_clock_gen.v
# - dir::../src/subservient/rtl/subservient_ram.v
# - dir::../src/subservient/rtl/subservient_rf_ram_if.v
# - dir::../src/subservient/rtl/subservient.v

# # Slightly smaller file sizes
# PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# # SDC files
# PNR_SDC_FILE: dir::chip_top.sdc
# SIGNOFF_SDC_FILE: dir::chip_top.sdc
# FALLBACK_SDC: dir::chip_top.sdc

# # Power / ground nets
# VDD_NETS:
# - VDD
# GND_NETS:
# - VSS

# # We need to add gf180mcu_fd_io__bi_24t
# # due to the unused Y output for output only pads
# SYNTH_DEFINES:
# - USE_POWER_PINS

# SYNTH_DEFINES:
# - USE_POWER_PINS

# IGNORE_DISCONNECTED_MODULES:
# - gf180mcu_fd_io__bi_24t
# - gf180mcu_ws_ip__id
# - gf180mcu_ws_ip__logo
# - gf180mcu_fd_ip_sram__sram512x8m8wm1

# # Clock
# CLOCK_PORT: clk_PAD
# CLOCK_NET: clk_pad/Y
# CLOCK_PERIOD: 40 # 25 MHz

# # Fix hold violations
# PL_RESIZER_HOLD_SLACK_MARGIN: 0.35
# GRT_RESIZER_HOLD_SLACK_MARGIN: 0.3

# # Increase for more logic on your die
# PL_TARGET_DENSITY_PCT: 35
# GRT_ALLOW_CONGESTION: true

# # Fix antenna violations after DRT
# DRT_ANTENNA_REPAIR_ITERS: 10
# DRT_ANTENNA_REPAIR_MARGIN: 10 # %

# # PDN - Straps
# PDN_VWIDTH: 5
# PDN_HWIDTH: 5
# PDN_VSPACING: 1
# PDN_HSPACING: 1
# PDN_VPITCH: 75
# PDN_HPITCH: 75

# # PDN - Core ring
# PDN_CORE_RING: True
# # Maximum metal width without slotting: 30um
# PDN_CORE_RING_VWIDTH: 25
# PDN_CORE_RING_HWIDTH: 25
# PDN_CORE_RING_CONNECT_TO_PADS: True
# PDN_ENABLE_PINS: False
# PDN_CORE_VERTICAL_LAYER: Metal2
# PDN_CORE_HORIZONTAL_LAYER: Metal3

# # Do not error on magic DRC violations
# ERROR_ON_MAGIC_DRC: False

# # Prevent false positive DRC errors in I/O cells
# MAGIC_GDS_FLATGLOB:
# - "*_CDNS_*"
# - "*$$*"
# - "M1_N*"
# - "M1_P*"
# - "M2_M1*"
# - "M3_M2*"
# - "nmos_5p0*"
# - "nmos_1p2*"
# - "pmos_5p0*"
# - "pmos_1p2*"
# - "via1_*"
# - "ypass_gate*"
# - "G_ring_*"
# - "dcap_103*"
# - "din_*"
# - "mux821_*"
# - "rdummy_*"
# - "pmoscap_*"
# - "xdec_*"
# - "ypredec*"
# - "xpredec*"
# - "prexdec_*"
# - "xdec8_*"
# - "xdec16_*"
# - "xdec32_*"
# - "sa_*"

# KLAYOUT_FILLER_OPTIONS:
#   Metal2_ignore_active: true

# MAGIC_EXT_UNIQUE: notopports

# MACROS:

#   gf180mcu_ws_ip__id:
#     gds:
#       - dir::../ip/gf180mcu_ws_ip__id/gds/gf180mcu_ws_ip__id.gds
#     lef:
#       - dir::../ip/gf180mcu_ws_ip__id/lef/gf180mcu_ws_ip__id.lef
#     vh:
#       - dir::../ip/gf180mcu_ws_ip__id/vh/gf180mcu_ws_ip__id.v
#     lib:
#       "*":
#         - dir::../ip/gf180mcu_ws_ip__id/lib/gf180mcu_ws_ip__id.lib
#     instances:
#       chip_id:
#         location: [26, 26]
#         orientation: N

#   gf180mcu_ws_ip__logo:
#     gds:
#       - dir::../ip/gf180mcu_ws_ip__logo/gds/gf180mcu_ws_ip__logo.gds
#     lef:
#       - dir::../ip/gf180mcu_ws_ip__logo/lef/gf180mcu_ws_ip__logo.lef
#     vh:
#       - dir::../ip/gf180mcu_ws_ip__logo/vh/gf180mcu_ws_ip__logo.v
#     lib:
#       "*":
#         - dir::../ip/gf180mcu_ws_ip__logo/lib/gf180mcu_ws_ip__logo.lib
#     instances:
#       wafer_space_logo:
#         location: ["expr::$DIE_AREA[2] + -169.25", "expr::$DIE_AREA[3] + -169.25"]
#         orientation: N

#   gf180mcu_fd_ip_sram__sram512x8m8wm1:
#     gds:
#       - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/gds/gf180mcu_fd_ip_sram__sram512x8m8wm1.gds
#     lef:
#       - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lef/gf180mcu_fd_ip_sram__sram512x8m8wm1.lef
#     vh:
#       - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/verilog/gf180mcu_fd_ip_sram__sram512x8m8wm1__blackbox.v
#     lib:
#       "*_tt_025C_5v00":
#         - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__tt_025C_5v00.lib
#       "*_ff_n40C_5v50":
#         - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__ff_n40C_5v50.lib
#       "*_ss_125C_4v50":
#         - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__ss_125C_4v50.lib
#     instances:
#       i_chip_core.noc_mesh.rows\[0\].cols\[0\].tile_inst.sram_lo: {location: [500,  500], orientation: N}
#       i_chip_core.noc_mesh.rows\[0\].cols\[0\].tile_inst.sram_hi: {location: [500,  700], orientation: N}
#       i_chip_core.noc_mesh.rows\[0\].cols\[1\].tile_inst.sram_lo: {location: [1500,  500], orientation: N}
#       i_chip_core.noc_mesh.rows\[0\].cols\[1\].tile_inst.sram_hi: {location: [1500,  700], orientation: N}
#       i_chip_core.noc_mesh.rows\[0\].cols\[2\].tile_inst.sram_lo: {location: [2500,  500], orientation: N}
#       i_chip_core.noc_mesh.rows\[0\].cols\[2\].tile_inst.sram_hi: {location: [2500,  700], orientation: N}
#       i_chip_core.noc_mesh.rows\[1\].cols\[0\].tile_inst.sram_lo: {location: [500,  1900], orientation: N}
#       i_chip_core.noc_mesh.rows\[1\].cols\[0\].tile_inst.sram_hi: {location: [500,  2100], orientation: N}
#       i_chip_core.noc_mesh.rows\[1\].cols\[1\].tile_inst.sram_lo: {location: [1500,  1900], orientation: N}
#       i_chip_core.noc_mesh.rows\[1\].cols\[1\].tile_inst.sram_hi: {location: [1500,  2100], orientation: N}
#       i_chip_core.noc_mesh.rows\[1\].cols\[2\].tile_inst.sram_lo: {location: [2500,  1900], orientation: N}
#       i_chip_core.noc_mesh.rows\[1\].cols\[2\].tile_inst.sram_hi: {location: [2500,  2100], orientation: N}
#       i_chip_core.noc_mesh.rows\[2\].cols\[0\].tile_inst.sram_lo: {location: [500,  3300], orientation: N}
#       i_chip_core.noc_mesh.rows\[2\].cols\[0\].tile_inst.sram_hi: {location: [500,  3500], orientation: N}
#       i_chip_core.noc_mesh.rows\[2\].cols\[1\].tile_inst.sram_lo: {location: [1500,  3300], orientation: N}
#       i_chip_core.noc_mesh.rows\[2\].cols\[1\].tile_inst.sram_hi: {location: [1500,  3500], orientation: N}
#       i_chip_core.noc_mesh.rows\[2\].cols\[2\].tile_inst.sram_lo: {location: [2500,  3300], orientation: N}
#       i_chip_core.noc_mesh.rows\[2\].cols\[2\].tile_inst.sram_hi: {location: [2500,  3500], orientation: N}


# # Halo size around macros while cutting rows.
# FP_MACRO_HORIZONTAL_HALO: 10
# FP_MACRO_VERTICAL_HALO: 10

# PDN_HORIZONTAL_HALO: 5
# PDN_VERTICAL_HALO: 5

# PDN_CFG: dir::pdn_cfg.tcl





############### NEW CONFIG FILE TEEEEHEEEE ###############


meta:
  version: 3
  flow: Chip
  substituting_steps:

    # Disable KLayout DRC
    #KLayout.DRC: null
    #Checker.KLayoutDRC: null

    # Disable KLayout antenna check
    #KLayout.Antenna: null
    #Checker.KLayoutAntenna: null

    # Disable KLayout density check
    #KLayout.Density: null
    #Checker.KLayoutDensity: null

    # Save time during development
    # Enable for sign-off
    #OpenROAD.IRDropReport: null
    #Magic.DRC: null
    #Checker.MagicDRC: null
    #KLayout.XOR: null
    #Netgen.LVS: null
    #Checker.LVS: null

DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::../src/chip_top.sv
- dir::../src/chip_core.sv
- dir::../src/boot_loader.v
- dir::../src/mesh_router.v
- dir::../src/mesh_tile.v
- dir::../src/mesh_3x3.v
- dir::../src/subservient_core.v
- dir::../src/serv/rtl/serv_aligner.v
- dir::../src/serv/rtl/serv_alu.v
- dir::../src/serv/rtl/serv_bufreg.v
- dir::../src/serv/rtl/serv_bufreg2.v
- dir::../src/serv/rtl/serv_compdec.v
- dir::../src/serv/rtl/serv_csr.v
- dir::../src/serv/rtl/serv_ctrl.v
- dir::../src/serv/rtl/serv_debug.v
- dir::../src/serv/rtl/serv_decode.v
- dir::../src/serv/rtl/serv_immdec.v
- dir::../src/serv/rtl/serv_mem_if.v
- dir::../src/serv/rtl/serv_rf_if.v
- dir::../src/serv/rtl/serv_rf_ram_if.v
- dir::../src/serv/rtl/serv_rf_ram.v
- dir::../src/serv/rtl/serv_rf_top.v
- dir::../src/serv/rtl/serv_state.v
- dir::../src/serv/rtl/serv_synth_wrapper.v
- dir::../src/serv/rtl/serv_top.v
- dir::../src/serv/servile/servile_arbiter.v
- dir::../src/serv/servile/servile_mux.v
- dir::../src/serv/servile/servile_rf_mem_if.v
- dir::../src/serv/servile/servile.v
- dir::../src/subservient/rtl/subservient_debug_switch.v
- dir::../src/subservient/rtl/subservient_fpga.v
- dir::../src/subservient/rtl/subservient_generic_ram.v
- dir::../src/subservient/rtl/subservient_gpio.v
- dir::../src/subservient/rtl/subservient_nexys_a7_clock_gen.v
- dir::../src/subservient/rtl/subservient_ram.v
- dir::../src/subservient/rtl/subservient_rf_ram_if.v
- dir::../src/subservient/rtl/subservient.v

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# SDC files
PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

VERILOG_DEFINES:
- USE_POWER_PINS
- NUM_DVDD_PADS=8
- NUM_DVSS_PADS=10
- NUM_INPUT_PADS=12
- NUM_BIDIR_PADS=40
- NUM_ANALOG_PADS=2


IGNORE_DISCONNECTED_MODULES:
- gf180mcu_fd_io__bi_24t
- gf180mcu_ws_ip__id
- gf180mcu_ws_ip__logo
- gf180mcu_fd_ip_sram__sram512x8m8wm1

# Clock
CLOCK_PORT: clk_PAD
CLOCK_NET: clk_pad/Y
CLOCK_PERIOD: 40 # 25 MHz

# Fix hold violations
PL_RESIZER_HOLD_SLACK_MARGIN: 0.35
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.3

# Increase for more logic on your die
PL_TARGET_DENSITY_PCT: 10 
GRT_ALLOW_CONGESTION: true

# Fix antenna violations after DRT
DRT_ANTENNA_REPAIR_ITERS: 10
DRT_ANTENNA_REPAIR_MARGIN: 10 # %

# PDN - Straps
PDN_VWIDTH: 5
PDN_HWIDTH: 5
PDN_VSPACING: 1
PDN_HSPACING: 1
PDN_VPITCH: 75
PDN_HPITCH: 75

# PDN - Core ring
PDN_CORE_RING: True
# Maximum metal width without slotting: 30um
PDN_CORE_RING_VWIDTH: 25
PDN_CORE_RING_HWIDTH: 25
PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_ENABLE_PINS: False
PDN_CORE_VERTICAL_LAYER: Metal2
PDN_CORE_HORIZONTAL_LAYER: Metal3

# Do not error on magic DRC violations
ERROR_ON_MAGIC_DRC: False

# Prevent false positive DRC errors in I/O cells
MAGIC_GDS_FLATGLOB:
- "*_CDNS_*"
- "*$$*"
- "M1_N*"
- "M1_P*"
- "M2_M1*"
- "M3_M2*"
- "nmos_5p0*"
- "nmos_1p2*"
- "pmos_5p0*"
- "pmos_1p2*"
- "via1_*"
- "ypass_gate*"
- "G_ring_*"
- "dcap_103*"
- "din_*"
- "mux821_*"
- "rdummy_*"
- "pmoscap_*"
- "xdec_*"
- "ypredec*"
- "xpredec*"
- "prexdec_*"
- "xdec8_*"
- "xdec16_*"
- "xdec32_*"
- "sa_*"

KLAYOUT_FILLER_OPTIONS:
  Metal2_ignore_active: true

MAGIC_EXT_UNIQUE: notopports

MACROS:

  gf180mcu_ws_ip__id:
    gds:
      - dir::../ip/gf180mcu_ws_ip__id/gds/gf180mcu_ws_ip__id.gds
    lef:
      - dir::../ip/gf180mcu_ws_ip__id/lef/gf180mcu_ws_ip__id.lef
    vh:
      - dir::../ip/gf180mcu_ws_ip__id/vh/gf180mcu_ws_ip__id.v
    lib:
      "*":
        - dir::../ip/gf180mcu_ws_ip__id/lib/gf180mcu_ws_ip__id.lib
    instances:
      chip_id:
        location: [26, 26]
        orientation: N

  gf180mcu_ws_ip__logo:
    gds:
      - dir::../ip/gf180mcu_ws_ip__logo/gds/gf180mcu_ws_ip__logo.gds
    lef:
      - dir::../ip/gf180mcu_ws_ip__logo/lef/gf180mcu_ws_ip__logo.lef
    vh:
      - dir::../ip/gf180mcu_ws_ip__logo/vh/gf180mcu_ws_ip__logo.v
    lib:
      "*":
        - dir::../ip/gf180mcu_ws_ip__logo/lib/gf180mcu_ws_ip__logo.lib
    instances:
      wafer_space_logo:
        location: ["expr::$DIE_AREA[2] + -169.25", "expr::$DIE_AREA[3] + -169.25"]
        orientation: N

  gf180mcu_fd_ip_sram__sram512x8m8wm1:
    gds:
      - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/gds/gf180mcu_fd_ip_sram__sram512x8m8wm1.gds
    lef:
      - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lef/gf180mcu_fd_ip_sram__sram512x8m8wm1.lef
    vh:
      - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/verilog/gf180mcu_fd_ip_sram__sram512x8m8wm1__blackbox.v
    lib:
      "*_tt_025C_5v00":
        - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__ss_125C_4v50.lib
    instances:
      i_chip_core.noc_mesh.rows[0].cols[0].tile_inst.sram_lo: {location: [502,  502],  orientation: N}
      i_chip_core.noc_mesh.rows[0].cols[0].tile_inst.sram_hi: {location: [502,  997],  orientation: N}
      i_chip_core.noc_mesh.rows[0].cols[1].tile_inst.sram_lo: {location: [1414, 502],  orientation: N}
      i_chip_core.noc_mesh.rows[0].cols[1].tile_inst.sram_hi: {location: [1414, 997],  orientation: N}
      i_chip_core.noc_mesh.rows[0].cols[2].tile_inst.sram_lo: {location: [2326, 502],  orientation: N}
      i_chip_core.noc_mesh.rows[0].cols[2].tile_inst.sram_hi: {location: [2326, 997],  orientation: N}
      i_chip_core.noc_mesh.rows[1].cols[0].tile_inst.sram_lo: {location: [502,  1656], orientation: N}
      i_chip_core.noc_mesh.rows[1].cols[0].tile_inst.sram_hi: {location: [502,  2151], orientation: N}
      i_chip_core.noc_mesh.rows[1].cols[1].tile_inst.sram_lo: {location: [1414, 1656], orientation: N}
      i_chip_core.noc_mesh.rows[1].cols[1].tile_inst.sram_hi: {location: [1414, 2151], orientation: N}
      i_chip_core.noc_mesh.rows[1].cols[2].tile_inst.sram_lo: {location: [2326, 1656], orientation: N}
      i_chip_core.noc_mesh.rows[1].cols[2].tile_inst.sram_hi: {location: [2326, 2151], orientation: N}
      i_chip_core.noc_mesh.rows[2].cols[0].tile_inst.sram_lo: {location: [502,  2810], orientation: N}
      i_chip_core.noc_mesh.rows[2].cols[0].tile_inst.sram_hi: {location: [502,  3305], orientation: N}
      i_chip_core.noc_mesh.rows[2].cols[1].tile_inst.sram_lo: {location: [1414, 2810], orientation: N}
      i_chip_core.noc_mesh.rows[2].cols[1].tile_inst.sram_hi: {location: [1414, 3305], orientation: N}
      i_chip_core.noc_mesh.rows[2].cols[2].tile_inst.sram_lo: {location: [2326, 2810], orientation: N}
      i_chip_core.noc_mesh.rows[2].cols[2].tile_inst.sram_hi: {location: [2326, 3305], orientation: N}
# Halo size around macros while cutting rows.
FP_MACRO_HORIZONTAL_HALO: 10
FP_MACRO_VERTICAL_HALO: 10
PDN_HORIZONTAL_HALO: 5
PDN_VERTICAL_HALO: 5

PDN_CFG: dir::pdn_cfg.tcl
